version: "3.9"

services:
  server_app:
    build:
      context: ../server/laravel/app
      dockerfile: ../server/laravel/app//dockerfile
    container_name: "php-app"
    ports:
      - 8080:8080

networks:
  app-network:
    driver: bridge